# Generated by Django 5.2.14 on 2026-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Ном')),
                ('platform_chat_id', models.CharField(blank=True, max_length=255, verbose_name='ID дар платформа')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чатҳо',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ном')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('avatar_url', models.URLField(blank=True)),
                ('platform_contact_id', models.CharField(blank=True, max_length=255, verbose_name='ID дар платформа')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контактҳо',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Фиристанда')),
                ('content', models.TextField(verbose_name='Матн')),
                ('message_type', models.CharField(default='text', max_length=20, verbose_name='Навъ')),
                ('sent_at', models.DateTimeField()),
                ('is_from_user', models.BooleanField(default=False, verbose_name='Аз ҷониби корбар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Паём',
                'verbose_name_plural': 'Паёмҳо',
                'ordering': ('sent_at',),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Ном')),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформаҳо',
            },
        ),
        migrations.CreateModel(
            name='SuggestedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(blank=True, verbose_name='Матни аслӣ')),
                ('suggested_text', models.TextField(verbose_name='Матни пешниҳодшуда')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('is_used', models.BooleanField(default=False, verbose_name='Истифода шуд')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ҷавоби пешниҳодшуда',
                'verbose_name_plural': 'Ҷавобҳои пешниҳодшуда',
            },
        ),
    ]
