# Generated by Django 5.2.14 on 2026-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('chat_history', models.TextField()),
                ('language', models.CharField(default='tg', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Дархости таҳлил',
                'verbose_name_plural': 'Дархостҳои таҳлил',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_reply', models.TextField()),
                ('context_summary', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Натиҷаи таҳлил',
                'verbose_name_plural': 'Натиҷаҳои таҳлил',
            },
        ),
    ]
